# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Build
  jobs:
  - job: Build 
    steps:
    - powershell: Get-ChildItem -Path $(Build.SourcesDirectory) -recurse
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        projects: '$(Build.SourcesDirectory)/Code/HDCDemo_Code/HDCDemo**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: '$(Build.SourcesDirectory)/Code/HDCDemo_Code/HDCDemo**/*.csproj'
        arguments: '--configuration Release'
