# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  repositories:
  - repository: repositoryTemplate
    type: git
    name: HDCDemo/YAMLTemplates

pool:
  vmImage: 'ubuntu-latest'

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
stages:
- stage: Build
  jobs:
    - template: Jobs/build.yml@repositoryTemplate
      parameters:
        solutionPath: 'Code/HDCDemo_Code'
        projectName: 'HDCDemo'
    - template: Tasks/ttk.yml@repositoryTemplate
      parameters:
        armTemplateLocation: 
        solutionPath: 'Infrastructure/HDCDemoApp'
        projectName: 'HDCDemoApp'
